title: WASA 2026
description: The 12th International Workshop on Autonomous Systems and Software Architecture
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
keywords: "workshops, automotive, software engineering, software architecture, autonomous systems"

# author settings for cc-by, appears in the footer
author: Stefan Kugele, Yanja Dajsuren, Alessio Bucaioni, and Jasmin JahiÄ‡
pub_year: 2026
github_username: stefankugele


